# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_extendrpolarsexamples_wrappers", use_symbols = TRUE, package_name = "extendrpolarsexamples")

#' @docType package
#' @usage NULL
#' @useDynLib extendrpolarsexamples, .registration = TRUE
NULL

#' export rpolars DataFrame from rust to rpolars
#' @return r-polars DataFrame
#' @details this function requires r-polars polars package >= 0.8.0.
#' @export
export_as_rpolars_df <- function() .Call(wrap__export_as_rpolars_df)

#' import rpolars DataFrame to rust and print back to R terminal
#' @param rdf r-polars DataFrame
#' @return NULL
#' @details this function requires r-polars polars package >= 0.8.0
#' @export
import_rpolars_df_and_print <- function(rdf) .Call(wrap__import_rpolars_df_and_print, rdf)

#' import rpolars DataFrame to rust and export again
#' @param rdf rpolars dataframe
#' @return rpolars dataframe
#' @details this function requires r-polars polars package >= 0.8.0
#' @export
test_round_trip <- function(rdf) .Call(wrap__test_round_trip, rdf)


# nolint end
