# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_extendrpolarsexamples_wrappers", use_symbols = TRUE, package_name = "extendrpolarsexamples")

#' @docType package
#' @usage NULL
#' @useDynLib extendrpolarsexamples, .registration = TRUE
NULL

#' show case zero copy export from rust-polars to r-polars
#' @details conversion via arrow stream such to ensure version compatability
#' @export
make_df <- function() .Call(wrap__make_df)


# nolint end
